### ISSUE TITLE
Multiple acts_as only builds one parent 

### ISSUE THREAD

**Issue by dafritz** [chaadow/active_record-acts_as#1]
I have a class which needs multiple parent associations. The acts_as class is set up to associate these of different keys, however it is only building the last association declared. 

```
  class MyObject < ApplicationRecord
    acts_as :maintainable_resource, class_name: "Maintenance::MaintainableResource", as: :maintainable, dependent: :destroy
    acts_as :schedulable_resource, class_name: "Schedule::SchedulableResource", as: :schedulable, dependent: :destroy
  end


```
This call only builds a ScheulableResource, not a MaintainableResource. Switching the order results in the opposite.

**Comment by manuelmeurer** [comment]
Sorry, but supporting multiple `acts_as` in the same class would require a major rewrite and complicate things quite a bit...
I'll add a note to the README that it's not supported for now.
