### ISSUE TITLE
It doesn't support with rails 5.1

### ISSUE THREAD

**Issue by eashward** [chaadow/active_record-acts_as#11]
I am getting this error 
ActiveRecord::HasManyThroughOrderError: Cannot have a has_many :through association 'Store#fulfillment' which goes through 'Store#service' before the through association is defined.

 I have this in models
class Store < ApplicationRecord
  acts_as :service
     has_one :fulfillment, class_name: 'Billing::Fulfillment', through: :service, dependent: :destroy
end

class Service < ApplicationRecord
  actable
end
the has_one association (has_one :store is build by gem itself), I don't know  what I am doing wrong. It works fine with rails 4.2 this issue is occurring when I Upgrade to rails 5.1

**Comment by manuelmeurer** [comment]
Thanks for the report @eashward and sorry for my late reply.
Is this still a problem for you or did you solve it somehow?
Could you please set up a small Rails app that demonstrates this error?
Thanks!

**Comment by abacha** [comment]
why this was closed? what was the solution? i`m having this issue with rails 5.1
