### ISSUE TITLE
Multiple Validation Errors for the same Attribute

### ISSUE THREAD

**Issue by barriault** [chaadow/active_record-acts_as#2]
ruby 2.3.3
rails 4.2.5

```ruby
class Party < ActiveRecord::Base
  actable
  validates :name, presence: true
end
```

```ruby
class Client < ActiveRecord::Base
  acts_as :party, dependent: :destroy
  validates :preferred_phone_number, presence: true
end
```

When I create a client with invalid attributes, my errors hash look like this:

```ruby
@messages={
  :name=>["can't be blank", "can't be blank", "can't be blank"], 
  :preferred_phone_number=>["can't be blank", "can't be blank"],
  :"actable.name"=>["can't be blank"],
  :"actable.preferred_phone_number"=>["can't be blank"]
}
```

This results in my errors on the form looking something like this:

10 errors prohibited this client from being saved:
* Name can't be blank
* Name can't be blank
* Name can't be blank
* Preferred phone number can't be blank
* Preferred phone number can't be blank
* Actable name can't be blank
* Actable preferred phone number can't be blank

This makes no sense . . .

**Comment by manuelmeurer** [comment]
Should be fixed in v2.3.0.
