### ISSUE TITLE
Finding by base model's ID

### ISSUE THREAD

**Issue by JasonBarnabe** [chaadow/active_record-acts_as#21]
`Pen.find(i)` will not necessarily be the same as `Product.find(i).specific` as the `pens` and `products` tables have different IDs. If I want to:

1. Only find `Pen`s
2. based on `Product` ID
3. and have it return `Pen` objects

Is there a better way to do this than something like `Pen.find_by(products: {id: i})`?

**Comment by manuelmeurer** [comment]
Nope, currently there's no better way.
If you have a suggestion and want to work on a PR, please reopen! 😀
