### ISSUE TITLE
Scopes from abstract model not working

### ISSUE THREAD

**Issue by chaadow** [chaadow/active_record-acts_as#22]
Hello,

I'm trying to access scopes/class_methods defined in the "parent", but from the child but i'm getting `NoMethodError: undefined method "scope_name"` 

For instance : `Product` has a `published` scope. and `Pen` is `acting_as` a `Product`. So I'm trying to call : `Pen.published`. and it does not work with the error mentionned above.

I'm using the latest version of the gem `active_record-acts_as (3.0.1)`
and `rails 5.2.0`

Is this feature implemented in the gem?
Thank you in advance

**Comment by manuelmeurer** [comment]
Yep, that should work. Can you post the relevant code?

**Comment by chaadow** [comment]
Sure. So first i tried setting up a minimalistic rails app from scratch, and it was working. So i knew it was application specific.
After looking at the source code, I discovered that the `active_record-acts_as` gem overrides the `self.scope` method like this : 
```ruby
     def self.callable_by_submodel(method)
            @methods_callable_by_submodel ||= Set.new
            @methods_callable_by_submodel << method
          end

          def self.scope(*)
            callable_by_submodel super
          end
```
whereas the other gem i'm using : [active_hash_relation](https://gitAhub.com/kollegorna/active_hash_relation/blob/master/lib/active_record/scope_names.rb)
overrides it like this : 
```ruby
       def scope(name, body, &block)
          @scope_names ||= []

          _scope(name, body, &block)

          @scope_names << name
        end
```
This code is executed before the other one, in an initializer, and is just setting a new "class instance variable" called `@@scope_names`. However it always returns an array.
And since the override of this gem is expecting the default return value of the default implementation of `self.scope` which is a symbol, the set is filled with arrays. 
for example, if there are three scopes called `published` `draft` `archived` then the set in `@@methods_callable_by_submodel` contains these elements : 
```ruby
 <Set: {[:draft, :published, :archived],
 [:draft, :published, :archived],
 [:draft, :published, :archived]}>
```
Similarly, the override of the `scope` method in this gem, always returns the current Set state. But since it is only scoped to the abstract model ( Like `Product` ) and not other models, It doesn't have the same impact as the other gem.

You could reimplement the override like this to preserve rails default output : 
```ruby
def self.scope(*)
  method = super
  callable_by_submodel method
  method
end
```
Would you mind me opening a pull request with this edit. I'm going to do the same in the other gem as well.

**Comment by manuelmeurer** [comment]
Sounds good, go ahead! :) Thanks for investigating.

**Comment by chaadow** [comment]
You're welcome. PR open 👌

**Comment by chaadow** [comment]
I'm going to close the issue.
