### ISSUE TITLE
Not working for rails 5.2.1

### ISSUE THREAD

**Issue by alfredorico** [chaadow/active_record-acts_as#25]
Hi. I have an issue with a very basic use case.
I just created two models as documented on README. Product and Pen
```
class CreateProducts < ActiveRecord::Migration[5.2]
  def change
    create_table :products do |t|
      t.actable      
      t.string :name
      t.integer :price

      t.timestamps
    end
  end
end
```
And Pen:
```
class CreatePens < ActiveRecord::Migration[5.2]
  def change
    create_table :pens do |t|
      t.string :color

    end
  end
end
```
Then in models:
```
class Product < ApplicationRecord
  actable
end
class Pen < ApplicationRecord
  acts_as :product
end
```
But when I try to create a Product I get following error:
```
2.5.1 :004 > x = Product.new(name: "Product", price: 5)
 => #<Product id: nil, actable_type: nil, actable_id: nil, name: "Product", price: 5, created_at: nil, updated_at: nil> 
2.5.1 :005 > x.valid?
 => false 
2.5.1 :006 > x.errors.messages
 => {:actable=>["must exist"]} 
2.5.1 :007 >
```
What am I wrong?
When creating a Pen, everything is ok. But I need create a Product!!! Please help.

**Comment by manuelmeurer** [comment]
You should use `Pen.new`, not `Product.new`.

**Comment by alfredorico** [comment]
Hi @manuelmeurer, thanks for answering.
Although, I wondering to know, why in rails 4.2.6 everything is worked as expected?
```
@thinkpad~: rails c
Running via Spring preloader in process 5642
Loading development environment (Rails 4.2.6)
2.2.4 :001 > x = Product.new(name: "Product", price: 5, actable: nil) => #<Product id: nil, actable_id: nil, actable_type: nil, name: "Product", price: 5, created_at: nil, updated_at: nil> 
2.2.4 :002 > x.valid?
 => true 
2.2.4 :003 > x.save
   (0.2ms)  begin transaction
  SQL (0.6ms)  INSERT INTO "products" ("name", "price", "created_at", "updated_at") VALUES (?, ?, ?, ?)  [["name", "Product"], ["price", 5], ["created_at", "2018-10-26 13:56:02.016898"], ["updated_at", "2018-10-26 13:56:02.016898"]]
   (9.8ms)  commit transaction
 => true 
2.2.4 :004 >
```
I think that this is the right behaviour. The main idea of MTI is to have a table parent with all common fields for all possible subclasses. But a parent class must be avoided for record creation?
Kind regards

**Comment by manuelmeurer** [comment]
Maybe because `belongs_to` relationships are mandatory from Rails 5 on?
Feel free to investigate and work on a PR to fix this.

**Comment by MatthewAger** [comment]
Just wanted to leave a comment for anyone else that comes across this - as `actable` takes the same args as `belongs_to`, to allow `Product.new` as well as `Pen.new` we can use

```
actable optional: true
```
