### ISSUE TITLE
Compatibility with Rails 5.2.2

### ISSUE THREAD

**Issue by milgner** [chaadow/active_record-acts_as#27]
It looks like `scope_for_create` was [recently changed in the Rails code](https://github.com/rails/rails/pull/33639/files), breaking the override in `ActiveRecord::ActsAs::ScopeForCreate`.

I haven't yet fully analysed the change but it seems like one is supposed to implement a separate method `values_for_create` instead. Did you already encounter this yourself and are working on this? Otherwise I'd check it out more thoroughly and create a PR some time in the next couple of days.

**Comment by manuelmeurer** [comment]
I'm actually not using this gem anymore, so feel free to look into this some more and of course a PR is more than welcome! 😄

**Comment by manuelmeurer** [comment]
Fixed by #29.
