### ISSUE TITLE
RubyGems.org has a version 4.0.0. Where is it? Is there a changelog?

### ISSUE THREAD

**Issue by fonji** [chaadow/active_record-acts_as#30]
[Here is the version on RubyGems.org](https://rubygems.org/gems/active_record-acts_as/versions/4.0.0) but I can't find a diff.
Is it official?
Did I miss something?

**Comment by manuelmeurer** [comment]
Fixed, I just forgot to push the latest commits and tags.
Will update the changelog later this week, please have a look at the diff for now.

**Comment by fonji** [comment]
Alright, thanks! I'll admit I was a little worried you got attacked :sweat_smile: 
Thanks for the lib, and have a nice day.
