### ISSUE TITLE
4.0.0 breaks find_or_initialize_by

### ISSUE THREAD

**Issue by grahamlyus** [chaadow/active_record-acts_as#31]
This doesn't happen with 3.1.0. The attributes are not being merged into the new object.

The problem appears to be in `scope_for_create`. I'm not an expert in the internals of rails, but perhaps something like this might be safer?

```
    module ScopeForCreate
      def scope_for_create(attributes = nil)
        return super unless acting_as?
        scope = respond_to?(:values_for_create) ? values_for_create(attributes) : where_values_hash
        scope.merge!(where_values_hash(acting_as_model.table_name))
        scope.merge!(attributes) if attributes
        scope.merge(create_with_value)
      end
    end
```

**Comment by manuelmeurer** [comment]
Thanks, @grahamlyus! I don't have time to work on this, but I'd be happy to help with getting a PR merged and released.
Could you start by adding a failing test?

**Comment by grahamlyus** [comment]
@manuelmeurer @tenshiAMD 

It looks like it works with 5.2.2 but not with 5.2.1. 

I created a test (https://github.com/grahamlyus/active_record-acts_as/commit/6afc5a3a83536d24c3b9b8516a3cb238a02ea35f), and it doesn't even run with 5.2.1 as `initialize_database` fails:
```
ActiveRecord::NotNullViolation:
  SQLite3::ConstraintException: NOT NULL constraint failed: ar_internal_metadata.key: INSERT INTO "ar_internal_metadata" ("value", "created_at", "updated_at") VALUES (?, ?, ?)
# ./spec/database_helper.rb:21:in `initialize_database'
# ./spec/models.rb:93:in `initialize_schema'
# ./spec/models.rb:154:in `<top (required)>'
# ./spec/rspec_matchers_spec.rb:1:in `<top (required)>'
# ------------------
# --- Caused by: ---
# SQLite3::ConstraintException:
#   NOT NULL constraint failed: ar_internal_metadata.key
#   ./spec/database_helper.rb:21:in `initialize_database'
```

This is due to `active_record/internal_metadata.rb` using `find_or_initialize_by`, so I suppose it's a good test in a way 😀

**Comment by manuelmeurer** [comment]
Great, thanks @grahamlyus! Did you try whether the test passes when you apply your changes to `scope_for_create`?

**Comment by grahamlyus** [comment]
I had to change it to specifically check for 5.2.1 (or 5.2.1.1) - these seem to be the only versions that take the `attributes`. Not sure if this is the best way to handle it.
