### ISSUE TITLE
Multiple nested forms and acts_as

### ISSUE THREAD

**Issue by nevrome** [chaadow/active_record-acts_as#34]
Thank you for this great gem. Very useful and reliable. Unfortunately I'm stuck right now and I hope you can point me to a general procedure to solve it.

I'm following [this](https://medium.com/@mindovermiles262/triple-nested-forms-in-rails-dedbcccb5799) guide to create a nested form. In this example one `show` has many `seasons` and one `season` has many `episodes`. Now imagine the `episode` model would be *actable*. `sad_episodes` *act_as* `episodes` and `funny_episodes` *act_as* `episodes` as well. How would I implement a nested form to create `shows` with `funny_episodes` or `sad_episodes`?

**Comment by manuelmeurer** [comment]
Thanks for the nice words, but unfortunately I cannot help you with implementing a nested form for your specific use-case. It should be straightforward though, since belongs_to/has_one is used behind the scene.
