### ISSUE TITLE
Please bump version for compatibility with ruby 2.7 

### ISSUE THREAD

**Issue by eric-unger** [chaadow/active_record-acts_as#37]
Hi, Thank you for creating this gem, its really useful, 
I currently updating the ruby version to 2.7 in a project, noticed that the master has the changes needed for warnings given with ruby 2.7, could you bump the version with the changes please

Thanks in advance

**Comment by manuelmeurer** [comment]
Have you tried the latest version 4.0.3?
It was released on July 14, 2020, and includes the latest changes.
The commit with the version bump was not pushed to GitHub yet.
