### ISSUE TITLE
.touch on submodel attributes

### ISSUE THREAD

**Issue by dezmathio** [chaadow/active_record-acts_as#4]
Hi friends! I've opened a pull request https://github.com/krautcomputing/active_record-acts_as/pull/3

Our problem:

We have some legacy infrastructure that needs `datetime` attributes on our submodels, in order to support that, we were wondering if we could support both cases? I'm confident my change will check for both cases and bubble them up to the proper submodel or supermodel.

I've also added some tests for sanity.

**Comment by dezmathio** [comment]
@manuelmeurer friendly nudge. Any thoughts?

**Comment by manuelmeurer** [comment]
Friendly nudge... :satisfied:

Please try v2.3.0.
