### ISSUE TITLE
Calling a method on supermodel with keyword arguments in ruby 3 results in ArgumentError

### ISSUE THREAD

**Issue by tindron** [chaadow/active_record-acts_as#43]
If a method like this is defined on the supermodel:
```ruby
def keyword_method(test: 1)
  'keyword_method'
end
```
In ruby 3, calling it from the submodel with kwargs results in an ArgumentError.

**Comment by tindron** [comment]
According to https://www.ruby-lang.org/en/news/2019/12/12/separation-of-positional-and-keyword-arguments-in-ruby-3-0/ the solution that works in ruby 2.5-3.0 is the ruby2_keywords gem.  I created #44 to resolve the issue.

**Comment by chaadow** [comment]
fixed in [5.0.3](https://rubygems.org/gems/active_record-acts_as/versions/5.0.3)
