### ISSUE TITLE
Actables class method does not restrict based on type

### ISSUE THREAD

**Issue by Taeir** [chaadow/active_record-acts_as#52]
The `actables` class method does not restrict based on actable type, so will actually return incorrect results.

For example, consider the following structure (using Product (base), Pen and Book from the Readme)
```ruby
Pen.create(name: 'Parker', price: 1.0, color: 'Black')
Book.create(name: 'Mystery', price: 1.0, color: 'Black')
Pen.where(color: 'Black').actables # => returns 2 products, including also the book!
```

**Comment by chaadow** [comment]
released in [v.5.2.0](https://rubygems.org/gems/active_record-acts_as/versions/5.2.0) @Taeir

**Comment by Taeir** [comment]
@chaadow Great, thanks for making the release!
