### ISSUE TITLE
_type column contains different value after shifting from acts_as_relation gem to active_record-acts_as gem

### ISSUE THREAD

**Issue by sanjaysalunkhe-ayla** [chaadow/active_record-acts_as#54]
I am upgrading rails project from rails 3.2.21 version to 5.2.8.  

Migration details.

```
class CreateDevices < ActiveRecord::Migration[6.0]
  def change
    create_table :devices do |t|
      t.actable as: :as_device
      t.timestamps
    end
  end
end

class CreateGateways < ActiveRecord::Migration[6.0]
  def change
    create_table :gateways do |t|
      t.actable as: :as_gateway
      t.timestamps
    end
  end
end

class CreateUserGrants < ActiveRecord::Migration[6.0]
  def change
    create_table :user_grants do |t|
      t.string :grantable_type
      t.string :grantable_id
      t.timestamps
    end
  end
end

```

I have below models.

```
class Device < ApplicationRecord
    actable as: :as_device
    has_many :user_grants, as: :grantable, dependent: :destroy, validate: false
end

class Gateway < ApplicationRecord
    actable as: :as_gateway
    acts_as :device, as: :as_device
    has_many :user_grants, as: :grantable, dependent: :destroy, validate: false
end

class UserGrant < ApplicationRecord
    belongs_to :grantable, polymorphic: true
end
```

Steps to create record in `user_grants` table. 

```
@device = Device.new
@device.save

@gateway = Gateway.new
@gateway.device = @device
@gateway.save

@gateway.user_grants.create
 #<UserGrant id: 3, grantable_type: "Gateway", grantable_id: "3", created_at: "2023-08-30 17:38:45", updated_at: "2023-08-30 17:38:45">
```

As per above output result user_grant record has grantable_type column value as "Gateway"  but when using acts_as_relation gem it is coming as "Device" .  is it bug in active_record-acts_as gem or active_record-acts_as gem has changed this behaviour intentionally ?

**Comment by chaadow** [comment]
hi @sanjaysalunkhe-ayla this gem only supports 6.x and above.

For rails 5.x, you can try this version of the gem [4.0.3](https://rubygems.org/gems/active_record-acts_as/versions/4.0.3)

**Comment by sanjaysalunkhe-ayla** [comment]
Hi @chaadow  i am using 4.0.3 version only..

**Comment by chaadow** [comment]
It was a while ago but yeah in this gem, the parent model ( here `Device` ) acts as a transparent/abstract layer whenever possible.

This allows Gateway to handle its own connections/associations with other models, and other models do not need to know that Gateway inherits from Device 

@sanjaysalunkhe-ayla
