### ISSUE TITLE
Namespace'd model support?

### ISSUE THREAD

**Issue by bpatram** [chaadow/active_record-acts_as#6]
Does this library work with namespace'd models? I've been having issues doing so. Below is a simplified version of my use case: 

Migration:
```ruby
   create_table :route_locations do |t|
      t.timestamps
      t.actable as: :locatable
      t.string :longitude
      t.string :latitude
    end

    # child of `routes_locations`
    create_table :route_named_locations do |t|
      t.string :name
    end
```

Models:
```ruby
class Route::Location < ApplicationRecord
  actable as: :locatable
end
```
```ruby
class Route::NamedLocation < ApplicationRecord
  acts_as :location, as: :locatable
end
```

When running `Route::NamedLocation.all` via rails console I get the following error: 
`NameError: uninitialized constant Location` which makes sense since I need `Route::Location` not just `Location` but I am unable to define it with the namespace. I've tried the following: 
- `acts_as :route_location, as: :locatable`
  - `NameError: uninitialized constant RouteLocation`
- `acts_as Route::Location, as: :locatable`
  - `TypeError: Route::Location(...) is not a symbol nor a string`
- `acts_as 'Route::Location', as: :locatable`
  - `ArgumentError: association names must be a Symbol`
- `acts_as :'Route::Location', as: :locatable`
  - `NameError: undefined local variable or method 'build_Route' for #<Module:0x000000035bde18>`

**Comment by bpatram** [comment]
I am running Rails 5.0.2, Ruby 2.3.3

It seems doing the following gets me closer, but I still run into another error:
```ruby
class Route::Location < ApplicationRecord
  actable as: :locatable
end
```
```ruby
class Route::NamedLocation < ApplicationRecord
  acts_as :location, as: :locatable, class_name: Route::Location.name
end
```

Running `Route::NamedLocation.all` runs just fine, but creating a new record `Route::NamedLocation.create(name: 'foo')` fails with:
`ActiveRecord::InverseOfAssociationNotFoundError: Could not find the inverse association for locatable ("route/location" in Route::NamedLocation)`

According to [Rails documentation](http://api.rubyonrails.org/classes/ActiveRecord/Associations/ClassMethods.html#method-i-has_one) for the `inverse_of` property for `has_one` relationships: 
> Does not work in combination with :through or :as options

**Comment by bpatram** [comment]
I am running Rails 5.0.2, Ruby 2.3.3

Okay, I seem to have this working. For anyone finding this thread later (maybe add to the README?):

Migration:
```ruby
   create_table :route_locations do |t|
      t.timestamps
      t.actable as: :locatable
      t.string :longitude
      t.string :latitude
    end

    # child of `routes_locations`
    create_table :route_named_locations do |t|
      t.string :name
    end
```

Models:
```ruby
class Route::Location < ApplicationRecord
  actable as: :locatable, inverse_of: :location
end
```
```ruby
class Route::NamedLocation < ApplicationRecord
  acts_as :location, as: :locatable, class_name: Route::Location.name
end
```

**Comment by manuelmeurer** [comment]
Thanks!

**Comment by Congrammers** [comment]
```
class Route::Location < ApplicationRecord
  actable inverse_of: :location
end
```

is not this limited? what should I pass to 'inverse_of' if there's multiple model with 'acts_as' that tried to 'inherit' from the same parent?
