### ISSUE TITLE
FactoryGirl actable Model

### ISSUE THREAD

**Issue by wafendy** [chaadow/active_record-acts_as#9]
Hi,

How do you create a valid factory for models with `actable`?

```
class MyApp::Product < ApplicationRecord
  actable inverse_of: :pen
end

class MyApp::Pen < ApplicationRecord
  acts_as :product, class_name: 'MyApp::Product'
end
```

This is what my factory looks like. 
```
FactoryGirl.define do
  factory :product, class: 'MyApp::Product' do
    name { FFaker::Name.name }
  end
end
```

And I'm getting the following error when running `FactoryGirl.lint`
`Validation failed: Actable must exist (ActiveRecord::RecordInvalid)`

**Comment by 6temes** [comment]
AFAIK, with FactoryGirl you would create a `Pen`, not a `Product`. 

At least, that's how I use it.

**Comment by manuelmeurer** [comment]
Yes, creating a product without a pen doesn't work. This has nothing to do with FactoryGirl AFAICS, if you tried `MyApp::Product.create!(name: FFaker::Name.name)` on the console you'd get the same error.

**Comment by wafendy** [comment]
👍

**Comment by wafendy** [comment]
thanks for the fast replies
